## Eager Execution


TensorFlow 引入了「Eager Execution」動態圖模式，這個模式在TensorFlow2.0為預設模式，不同與以往的靜態圖模式需要建立計算圖才能執行，Eager Execution模式一旦執行就會返回數值。這使TensorFlow 更容易入門，也使研發更直觀。

**Eager Execution 的優點如下：**

- 立即返回數值，方便除錯。
- 無需 Session.run() 就可以把它們的值返回到 Python。
- 為自定義和高階梯度提供強大支援。
- 幾乎所有 TensorFlow 運算都適用。

**TensorFlow 1.x 和 TensorFlow2.0比較：**
```
TensorFlow 1.x code:
>>> a = tf.constant(1)
>>> print(a)
Tensor("Const_5:0", shape=(), dtype=int32)

>>> sess = tf.Session()
>>> print("a = {}".format(sess.run(a)))
a = 1


TensorFlow 2.0 code:
>>> a = tf.constant(1)
>>> print(a)
tf.Tensor(1, shape=(), dtype=int32)
```

In [ ]:
# TensorFlow 1.0 code
import tensorflow as tf

a = tf.constant(5, name="input_a")
b = tf.constant(3, name="input_b")
c = tf.multiply(a, b, name="mul_c")
d = tf.add(a, b, name="add_d")
e = tf.add(c, d, name="add_e")

with tf.Session() as sess:
    print(sess.run(e)) # output => 23

![Alt text](./images/basic_tensorflow/computation_graph.png)

In [1]:
import numpy as np
import tensorflow as tf

print("Eager Execution 是否啟動: {}".format(tf.executing_eagerly()))

Eager Execution 是否啟動: True


In [3]:
a = tf.constant(3)
b = tf.constant(4)
print(a)
print(a.numpy())
print(b)
print("a = {}".format(a))
print("b = {}".format(b))

tf.Tensor(3, shape=(), dtype=int32)
3
tf.Tensor(4, shape=(), dtype=int32)
a = 3
b = 4


In [7]:
x = tf.constant([[1, 2],[3, 4]], name='x')
y = tf.constant([[5, 6],[7, 8]], name='y')

tf_sum = x + y
tf_sub = x - y
tf_mul = x * y
tf_div = x / y
tf_mod = x % y
tf_neg = -x

print("x: {}\n".format(x))
print("y: {}\n".format(y))
print("tf_sum: {}\n".format(tf_sum))
print("tf_sub: {}\n".format(tf_sub))
print("tf_mul: {}\n".format(tf_mul))
print("tf_div: {}\n".format(tf_div))
print("tf_mod: {}\n".format(tf_mod))
print("tf_neg: {}\n".format(tf_neg))

x: [[1 2]
 [3 4]]

y: [[5 6]
 [7 8]]

tf_sum: [[ 6  8]
 [10 12]]

tf_sub: [[-4 -4]
 [-4 -4]]

tf_mul: [[ 5 12]
 [21 32]]

tf_div: [[0.2        0.33333333]
 [0.42857143 0.5       ]]

tf_mod: [[1 2]
 [3 4]]

tf_neg: [[-1 -2]
 [-3 -4]]



#### tf_sum = tf.math.add(x, y)
#### tf_sub = tf.math.subtract(x, y)
#### tf_mul = tf.math.multiply(x, y)
#### tf_div = tf.math.divide(x,y)
#### tf_mod = tf.math.mod(x,y)
#### tf_neg = tf.math.negative(x)

In [4]:
import tensorflow as tf
x = tf.constant([[1, 2],[3, 4]], name='x')
y = tf.constant([[5, 6],[7, 8]], name='y')

tf_sum = tf.math.add(x, y)
tf_sub = tf.math.subtract(x, y)
tf_mul = tf.math.multiply(x, y)
tf_div = tf.math.divide(x,y)
tf_mod = tf.math.mod(x,y)
tf_neg = tf.math.negative(x)


print("x: {}\n".format(x))
print("y: {}\n".format(y))
print("tf_sum: {}\n".format(tf_sum))
print("tf_sub: {}\n".format(tf_sub))
print("tf_mul: {}\n".format(tf_mul))
print("tf_div: {}\n".format(tf_div))
print("tf_mod: {}\n".format(tf_mod))
print("tf_neg: {}\n".format(tf_neg))

x: [[1 2]
 [3 4]]

y: [[5 6]
 [7 8]]

tf_sum: [[ 6  8]
 [10 12]]

tf_sub: [[-4 -4]
 [-4 -4]]

tf_mul: [[ 5 12]
 [21 32]]

tf_div: [[0.2        0.33333333]
 [0.42857143 0.5       ]]

tf_mod: [[1 2]
 [3 4]]

tf_neg: [[-1 -2]
 [-3 -4]]



#### tf.linalg.matmul( )
#### tf.linalg.inv(matrix1)
#### tf.linalg.matrix_transpose(matrix1)

In [13]:
matrix1 = tf.constant([[1.0, 2.0],[3.0, 4.0]], name='x')
matrix2 = tf.constant([[5.0, 6.0],[7.0, 8.0]], name='y')

product = tf.linalg.matmul(matrix1, matrix2)
inv = tf.linalg.inv(matrix1)
trans = tf.linalg.matrix_transpose(matrix1)

print("product: {}\n".format(product))
print("inv: {}\n".format(inv))
print("trans: {}\n".format(trans))

product: [[19. 22.]
 [43. 50.]]

inv: [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

trans: [[1. 3.]
 [2. 4.]]



# Tensor Type
There are many data type in tensorflow. Following list some common type. If you want to change the type of tensor, ```tf.cast()``` can help. Please reference the following code.

| Python type | Description |  
| :------: | :------: |  
| tf.float32 | 32 bits floating point |
| tf.float64 | 64 bits floating point |
| tf.int8 | 8 bits signed integer |
| tf.int16 | 16 bits signed integer |
| tf.int32 | 32 bits signed integer |
| tf.int64 | 64 bits signed integer |
| tf.uint8 | 8 bits unsigned integer |
| tf.uint16 | 16 bits unsigned integer |
| tf.string | Variable length byte arrays. Each element of a Tensor is a byte array |
| tf.bool | Boolean |

#### tf.dtypes.cast(x_float, tf.int32)

In [15]:
x_float = tf.constant([1.8, 2.2], dtype=tf.float32)
x_int = tf.dtypes.cast(x_float, tf.int32)

print("x_int: {}\n".format(x_int))

x_int: [1 2]



# Random Function

In [8]:
random1 = tf.constant(tf.random.normal([2,3],  mean=0.0, stddev=0.1))
random2 = tf.constant(tf.random.truncated_normal([2,3],  mean=0.0, stddev=0.1))
random3 = tf.constant(tf.random.uniform([2,3], minval=0, maxval=100))

print('random1: {}'.format(random1))
print('random2: {}'.format(random2))
print('random3: {}'.format(random3))

random1: [[-0.0614919  -0.0012403  -0.03223115]
 [ 0.18066007  0.15610538 -0.04368369]]
random2: [[-0.09070393 -0.00948893 -0.00205547]
 [ 0.1233022  -0.02860755 -0.02131384]]
random3: [[88.51293   80.25347    2.0477772]
 [73.02084   38.05113   64.043106 ]]


# Constant Function

In [12]:
c1 = tf.zeros([2,1])
c2 = tf.ones([2,3])
c3 = tf.fill([2,4], 9)
c4 = tf.constant([2.0,1.0])

print('c1: {}'.format(c1))
print('c2: {}'.format(c2))
print('c3: {}'.format(c3))
print('c4: {}'.format(c4))


c1: [[0.]
 [0.]]
c2: [[1. 1. 1.]
 [1. 1. 1.]]
c3: [[9 9 9 9]
 [9 9 9 9]]
c4: [2. 1.]


# Constant/Variable  
Constant, variable, and placeholder can be set like the following. The difference among them is that 
1. constant can't be changed once define
2. variable would change while learning. It need to be initialized by constant tensorflow.

In [14]:
x_constant1 = tf.constant([[1.1, 2.2],[3.3, 4.4]], dtype=tf.float32) # define float32 tensor
x_constant2 = tf.zeros([2,3])
x_constant3 = tf.random.normal([1,3], stddev=1)

x_variable1 = tf.Variable(tf.constant([[1.1, 2.2],[3.3, 4.4]], dtype=tf.float32))
x_variable2 = tf.Variable(tf.zeros([2,3]))
x_variable3 = tf.Variable(tf.random.normal([1,3], stddev=1))

print(x_constant1)
print(x_constant2)
print(x_constant3)

print(x_variable1)
print(x_variable2)
print(x_variable3)

tf.Tensor(
[[1.1 2.2]
 [3.3 4.4]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor([[ 0.85268366 -0.38222453  0.80098224]], shape=(1, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1.1, 2.2],
       [3.3, 4.4]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[-0.12044986,  0.9084426 , -0.9926602 ]], dtype=float32)>


#### tf.reduce_mean(x)數據平均值
#### tf.reduce_sum(x)數據加總
#### tf.math.abs(x)數據絕對值

# Common Function

In [2]:
import tensorflow as tf
x = tf.constant([[1., 5.], [-2., 3.]])
result1 = tf.reduce_mean(x)
result2 = tf.reduce_sum(x)
result3 = tf.math.abs(x)
print("result1: {}".format(result1))
print("result2: {}".format(result2))
print("result3: {}".format(result3))


result1: 1.75
result2: 7.0
result3: [[1. 5.]
 [2. 3.]]


#### tf.math.argmax( ) tf.math.argmin( )回傳數字組最大或最小的index

In [19]:
test =tf.constant([[1.1, 2.2, 3.3],[4.5, 3.2, 2.1], [5, 0, -2]], dtype=tf.float32)
arg_max = tf.math.argmax(test)
arg_min = tf.math.argmin(test)
print("arg_max: {}".format(arg_max))
print("arg_min: {}".format(arg_min))

arg_max: [2 1 0]
arg_min: [0 2 2]


## Unstack

### unstack at axis = 0
![Alt text](./images/basic_tensorflow/unstack_axis0.png)
### unstack at axis = 1
![Alt text](./images/basic_tensorflow/unstack_axis1.png)
### unstack at axis = 2
![Alt text](./images/basic_tensorflow/unstack_axis2.png)

In [21]:
x = tf.constant([[0.7,0.9],[0.1,0.4],[0.5,0.8]], name='x')
axis0_x = tf.unstack(x, axis=0)


print(axis0_x[0])
print(axis0_x[1])
print(axis0_x[2])

tf.Tensor([0.7 0.9], shape=(2,), dtype=float32)
tf.Tensor([0.1 0.4], shape=(2,), dtype=float32)
tf.Tensor([0.5 0.8], shape=(2,), dtype=float32)


## Stack

### origin data
![Alt text](./images/basic_tensorflow/stack_origin.png)
### stack at axis = 0
![Alt text](./images/basic_tensorflow/stack_axis0.png)
### stack at axis = 1
![Alt text](./images/basic_tensorflow/stack_axis1.png)

In [24]:
x = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], name='x')
y = tf.constant([[1.0, 1.0], [0.0, 1.0], [1.0, 1.0]], name='y')

stacked_axis0_result = tf.stack([x,y], axis=0)
stacked_axis1_result = tf.stack([x,y], axis=1)


print(stacked_axis0_result)
print(stacked_axis0_result.shape)
    
print(stacked_axis1_result)
print(stacked_axis1_result.shape)

tf.Tensor(
[[[1. 2.]
  [3. 4.]
  [5. 6.]]

 [[1. 1.]
  [0. 1.]
  [1. 1.]]], shape=(2, 3, 2), dtype=float32)
(2, 3, 2)
tf.Tensor(
[[[1. 2.]
  [1. 1.]]

 [[3. 4.]
  [0. 1.]]

 [[5. 6.]
  [1. 1.]]], shape=(3, 2, 2), dtype=float32)
(3, 2, 2)


# TensorFlow Data
#### TensorFlow2才有的 用for loop取出元素

In [57]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
for elem in dataset:
    print(elem.numpy())

8
3
0
8
2
1


In [4]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
it = iter(dataset)

print(next(it).numpy())
print(next(it).numpy())
print(next(it).numpy())

8
3
0


In [2]:
import tensorflow as tf
x_data = tf.data.Dataset.from_tensor_slices([0, 1, 2, 3, 4, 5])
y_data = tf.data.Dataset.from_tensor_slices([0, 2, 4, 6, 8, 10])

for data1, data2 in zip(x_data, y_data):
    print('x: {}, y: {}'.format(data1, data2))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4
x: 3, y: 6
x: 4, y: 8
x: 5, y: 10


## .take(3)取到第三個

In [5]:
x_data = tf.data.Dataset.from_tensor_slices([0, 1, 2, 3, 4, 5])
y_data = tf.data.Dataset.from_tensor_slices([0, 2, 4, 6, 8, 10])

for data1, data2 in zip(x_data.take(3), y_data.take(3)):
    print('x: {}, y: {}'.format(data1, data2))

x: 0, y: 0
x: 1, y: 2
x: 2, y: 4


# Gradient  

#### 去作微分 w初始值2 with tf.GradientTape( ) as t: 把想要微分的函數寫在裡面loss=w*w
#### 用t.gradient(loss,w) 用 loss 針對 w作微分
#### w 的平方的微分 2w 
- 只能call 一次 t.gradient(loss,w) 不能第二次 會出錯

In [23]:
w = tf.Variable(tf.constant([2.0]))

with tf.GradientTape() as t:
    loss = w * w
grad = t.gradient(loss,w)
print(grad)

#grad = t.gradient(loss,w)

tf.Tensor([4.], shape=(1,), dtype=float32)


#### persistent=True 就能call多次 t.gradient(loss,w)

In [26]:
w = tf.Variable(tf.constant([2.0]))

with tf.GradientTape(persistent=True) as t:
    loss = w * w
grad = t.gradient(loss,w)
print(grad)
grad = t.gradient(loss,w)
print(grad)
del t

tf.Tensor([4.], shape=(1,), dtype=float32)
tf.Tensor([4.], shape=(1,), dtype=float32)


#### tf.constant([2.0])作微分 要加上t.watch(w)
#### tf.Variable(tf.constant([2.0]))則不用

In [21]:
w = tf.constant([2.0])

with tf.GradientTape() as t:
    t.watch(w)
    loss = w * w
grad = t.gradient(loss,w)
print(grad)

#grad = t.gradient(loss,w)

tf.Tensor([2.], shape=(1,), dtype=float32)


# Optimization - method 1

In [44]:
import tensorflow as tf

def fu_minimzie():
    return 2*x*x + x + 3 

x = tf.Variable(1.0) 

opt = tf.keras.optimizers.SGD(learning_rate=0.01)
#opt = tf.keras.optimizers.Adagrad(learning_rate=0.01)
#opt = tf.keras.optimizers.Adam(learning_rate=0.01)
#opt = tf.keras.optimizers.RMSprop(learning_rate=0.01)
for i in range(1000):
    opt.minimize(fu_minimzie, var_list=[x])
print('x: {}'.format(x.numpy()))
print('y: {}'.format(y.numpy()))


x: -0.25
y: 6.0


# Optimization - method 2

In [3]:

x = tf.Variable(1.0) 

opt = tf.keras.optimizers.SGD(learning_rate=0.1)
for i in range(1000):

    with tf.GradientTape() as tape:
        y = 2*x*x + x + 3 
    grads = tape.gradient(y, [x])
    processed_grads = [g for g in grads]
    grads_and_vars = zip(processed_grads, [x])
#    print('y = {}, x = {}, grads = {} '.format(y.numpy(), x.numpy(), grads[0].numpy()))
    
    opt.apply_gradients(grads_and_vars)
print('x: {}'.format(x.numpy()))
print('y: {}'.format(y.numpy()))


x: -0.2499999850988388
y: 2.875


# Optimization - method 3

In [55]:
x = tf.Variable(1.0) 

for i in range(50):
    with tf.GradientTape() as tape:
        y = 2*x*x + x + 3 
    grads = tape.gradient(y, [x])
#    print('y = {}, x = {}, grads = {} '.format(y.numpy(), x.numpy(), grads[0].numpy()))
    x.assign(x - 0.1*grads[0].numpy())
print('x: {}'.format(x.numpy()))
print('y: {}'.format(y.numpy()))

x: -0.2499999850988388
y: 2.875
